version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: MYBD
      POSTGRES_USER: king
      POSTGRES_PASSWORD: BM71004!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    command: /bin/sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A celery_app. worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
