name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: king
          POSTGRES_PASSWORD: BM71004!
          POSTGRES_DB: MYBD
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r First_task/requirements.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://king:BM71004!@localhost:5432/MYBD
          REDIS_URL: redis://localhost:6379/0
          SECRET_KEY: L7ZG_-M_yyRnmiXAwG1ZbO9T9Xt6wui_68DyIPrvows
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
        run: |
          pytest

      - name: Build Docker image
        run: docker build -t fastapi-app .